package com.dothings.model;

import java.util.Date;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.ACTIVITY_TYPE
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String activityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.award
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Double award;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.create_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.photo_link
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String photoLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.title
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.visibility
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String visibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.created_by
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.description
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.ACTIVITY_TYPE
     *
     * @return the value of activity.ACTIVITY_TYPE
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getActivityType() {
        return activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.ACTIVITY_TYPE
     *
     * @param activityType the value for activity.ACTIVITY_TYPE
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setActivityType(String activityType) {
        this.activityType = activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.award
     *
     * @return the value of activity.award
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Double getAward() {
        return award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.award
     *
     * @param award the value for activity.award
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setAward(Double award) {
        this.award = award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.create_date
     *
     * @return the value of activity.create_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.create_date
     *
     * @param createDate the value for activity.create_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.photo_link
     *
     * @return the value of activity.photo_link
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getPhotoLink() {
        return photoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.photo_link
     *
     * @param photoLink the value for activity.photo_link
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setPhotoLink(String photoLink) {
        this.photoLink = photoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.title
     *
     * @return the value of activity.title
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.title
     *
     * @param title the value for activity.title
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.visibility
     *
     * @return the value of activity.visibility
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getVisibility() {
        return visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.visibility
     *
     * @param visibility the value for activity.visibility
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setVisibility(String visibility) {
        this.visibility = visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.created_by
     *
     * @return the value of activity.created_by
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.created_by
     *
     * @param createdBy the value for activity.created_by
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.description
     *
     * @return the value of activity.description
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.description
     *
     * @param description the value for activity.description
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", activityType=").append(activityType);
        sb.append(", award=").append(award);
        sb.append(", createDate=").append(createDate);
        sb.append(", photoLink=").append(photoLink);
        sb.append(", title=").append(title);
        sb.append(", visibility=").append(visibility);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }
}