package com.dothings.model;

import java.util.Date;

public class Comments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.COMMENT
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.DATE
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.event_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.user_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.visible
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Boolean visible;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.COMMENT
     *
     * @return the value of comments.COMMENT
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.COMMENT
     *
     * @param comment the value for comments.COMMENT
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.DATE
     *
     * @return the value of comments.DATE
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.DATE
     *
     * @param date the value for comments.DATE
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.event_id
     *
     * @return the value of comments.event_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.event_id
     *
     * @param eventId the value for comments.event_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.user_id
     *
     * @return the value of comments.user_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.user_id
     *
     * @param userId the value for comments.user_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.visible
     *
     * @return the value of comments.visible
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Boolean getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.visible
     *
     * @param visible the value for comments.visible
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", comment=").append(comment);
        sb.append(", date=").append(date);
        sb.append(", eventId=").append(eventId);
        sb.append(", userId=").append(userId);
        sb.append(", visible=").append(visible);
        sb.append("]");
        return sb.toString();
    }
}