package com.dothings.model;

import java.util.Date;

public class Event {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.address
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.creation_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.creator_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.description
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date eventDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.end_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.start_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_type
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.loc_Lat
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String locLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.loc_long
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String locLong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.picture
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.summary
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.loc_lon
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String locLon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.id
     *
     * @return the value of event.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.id
     *
     * @param id the value for event.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.address
     *
     * @return the value of event.address
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.address
     *
     * @param address the value for event.address
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.creation_date
     *
     * @return the value of event.creation_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.creation_date
     *
     * @param creationDate the value for event.creation_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.creator_id
     *
     * @return the value of event.creator_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.creator_id
     *
     * @param creatorId the value for event.creator_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.description
     *
     * @return the value of event.description
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.description
     *
     * @param description the value for event.description
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_date
     *
     * @return the value of event.event_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getEventDate() {
        return eventDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_date
     *
     * @param eventDate the value for event.event_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.end_date
     *
     * @return the value of event.end_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.end_date
     *
     * @param endDate the value for event.end_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.start_date
     *
     * @return the value of event.start_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.start_date
     *
     * @param startDate the value for event.start_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_type
     *
     * @return the value of event.event_type
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_type
     *
     * @param eventType the value for event.event_type
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.loc_Lat
     *
     * @return the value of event.loc_Lat
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getLocLat() {
        return locLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.loc_Lat
     *
     * @param locLat the value for event.loc_Lat
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setLocLat(String locLat) {
        this.locLat = locLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.loc_long
     *
     * @return the value of event.loc_long
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getLocLong() {
        return locLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.loc_long
     *
     * @param locLong the value for event.loc_long
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setLocLong(String locLong) {
        this.locLong = locLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.picture
     *
     * @return the value of event.picture
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.picture
     *
     * @param picture the value for event.picture
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.summary
     *
     * @return the value of event.summary
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.summary
     *
     * @param summary the value for event.summary
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.loc_lon
     *
     * @return the value of event.loc_lon
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getLocLon() {
        return locLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.loc_lon
     *
     * @param locLon the value for event.loc_lon
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setLocLon(String locLon) {
        this.locLon = locLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", address=").append(address);
        sb.append(", creationDate=").append(creationDate);
        sb.append(", creatorId=").append(creatorId);
        sb.append(", description=").append(description);
        sb.append(", eventDate=").append(eventDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", startDate=").append(startDate);
        sb.append(", eventType=").append(eventType);
        sb.append(", locLat=").append(locLat);
        sb.append(", locLong=").append(locLong);
        sb.append(", picture=").append(picture);
        sb.append(", summary=").append(summary);
        sb.append(", locLon=").append(locLon);
        sb.append("]");
        return sb.toString();
    }
}