package com.dothings.model;

import java.util.Date;

public class HappyHour {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happy_hour.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happy_hour.loc_lat
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String locLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happy_hour.loc_lon
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String locLon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happy_hour.start_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date startDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happy_hour.id
     *
     * @return the value of happy_hour.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happy_hour.id
     *
     * @param id the value for happy_hour.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happy_hour.loc_lat
     *
     * @return the value of happy_hour.loc_lat
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getLocLat() {
        return locLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happy_hour.loc_lat
     *
     * @param locLat the value for happy_hour.loc_lat
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setLocLat(String locLat) {
        this.locLat = locLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happy_hour.loc_lon
     *
     * @return the value of happy_hour.loc_lon
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getLocLon() {
        return locLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happy_hour.loc_lon
     *
     * @param locLon the value for happy_hour.loc_lon
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setLocLon(String locLon) {
        this.locLon = locLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happy_hour.start_date
     *
     * @return the value of happy_hour.start_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happy_hour.start_date
     *
     * @param startDate the value for happy_hour.start_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happy_hour
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", locLat=").append(locLat);
        sb.append(", locLon=").append(locLon);
        sb.append(", startDate=").append(startDate);
        sb.append("]");
        return sb.toString();
    }
}