package com.dothings.model;

import java.util.Date;

public class HealthDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_detail.id
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_detail.create_date
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_detail.type
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_detail.value
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    private Double value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_detail.USER
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    private Long user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_detail.id
     *
     * @return the value of health_detail.id
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_detail.id
     *
     * @param id the value for health_detail.id
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_detail.create_date
     *
     * @return the value of health_detail.create_date
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_detail.create_date
     *
     * @param createDate the value for health_detail.create_date
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_detail.type
     *
     * @return the value of health_detail.type
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_detail.type
     *
     * @param type the value for health_detail.type
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_detail.value
     *
     * @return the value of health_detail.value
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_detail.value
     *
     * @param value the value for health_detail.value
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    public void setValue(Double value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_detail.USER
     *
     * @return the value of health_detail.USER
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    public Long getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_detail.USER
     *
     * @param user the value for health_detail.USER
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    public void setUser(Long user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_detail
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createDate=").append(createDate);
        sb.append(", type=").append(type);
        sb.append(", value=").append(value);
        sb.append(", user=").append(user);
        sb.append("]");
        return sb.toString();
    }
}