package com.dothings.model;

import java.util.Date;

public class Poll {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll.answer1
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String answer1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll.answer2
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String answer2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll.answer3
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String answer3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll.answer4
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String answer4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll.end_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll.start_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll.survey_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long surveyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll.id
     *
     * @return the value of poll.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll.id
     *
     * @param id the value for poll.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll.answer1
     *
     * @return the value of poll.answer1
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getAnswer1() {
        return answer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll.answer1
     *
     * @param answer1 the value for poll.answer1
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setAnswer1(String answer1) {
        this.answer1 = answer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll.answer2
     *
     * @return the value of poll.answer2
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getAnswer2() {
        return answer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll.answer2
     *
     * @param answer2 the value for poll.answer2
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setAnswer2(String answer2) {
        this.answer2 = answer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll.answer3
     *
     * @return the value of poll.answer3
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getAnswer3() {
        return answer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll.answer3
     *
     * @param answer3 the value for poll.answer3
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setAnswer3(String answer3) {
        this.answer3 = answer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll.answer4
     *
     * @return the value of poll.answer4
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getAnswer4() {
        return answer4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll.answer4
     *
     * @param answer4 the value for poll.answer4
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setAnswer4(String answer4) {
        this.answer4 = answer4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll.end_date
     *
     * @return the value of poll.end_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll.end_date
     *
     * @param endDate the value for poll.end_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll.start_date
     *
     * @return the value of poll.start_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll.start_date
     *
     * @param startDate the value for poll.start_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll.survey_id
     *
     * @return the value of poll.survey_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getSurveyId() {
        return surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll.survey_id
     *
     * @param surveyId the value for poll.survey_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setSurveyId(Long surveyId) {
        this.surveyId = surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", answer1=").append(answer1);
        sb.append(", answer2=").append(answer2);
        sb.append(", answer3=").append(answer3);
        sb.append(", answer4=").append(answer4);
        sb.append(", endDate=").append(endDate);
        sb.append(", startDate=").append(startDate);
        sb.append(", surveyId=").append(surveyId);
        sb.append("]");
        return sb.toString();
    }
}