package com.dothings.model;

public class PollAnswer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_answer.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_answer.answer
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Integer answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_answer.USER
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_answer.id
     *
     * @return the value of poll_answer.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_answer.id
     *
     * @param id the value for poll_answer.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_answer.answer
     *
     * @return the value of poll_answer.answer
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Integer getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_answer.answer
     *
     * @param answer the value for poll_answer.answer
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setAnswer(Integer answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_answer.USER
     *
     * @return the value of poll_answer.USER
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_answer.USER
     *
     * @param user the value for poll_answer.USER
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setUser(Long user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", answer=").append(answer);
        sb.append(", user=").append(user);
        sb.append("]");
        return sb.toString();
    }
}