package com.dothings.model;

public class Profile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.picture
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.rank
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.score
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.user_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.id
     *
     * @return the value of profile.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.id
     *
     * @param id the value for profile.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.picture
     *
     * @return the value of profile.picture
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.picture
     *
     * @param picture the value for profile.picture
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.rank
     *
     * @return the value of profile.rank
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.rank
     *
     * @param rank the value for profile.rank
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.score
     *
     * @return the value of profile.score
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.score
     *
     * @param score the value for profile.score
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.user_id
     *
     * @return the value of profile.user_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.user_id
     *
     * @param userId the value for profile.user_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", picture=").append(picture);
        sb.append(", rank=").append(rank);
        sb.append(", score=").append(score);
        sb.append(", userId=").append(userId);
        sb.append("]");
        return sb.toString();
    }
}