package com.dothings.model;

public class QuestCompletion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_completion.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_completion.photo_link
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String photoLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_completion.quest
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long quest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_completion.USER
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_completion.id
     *
     * @return the value of quest_completion.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_completion.id
     *
     * @param id the value for quest_completion.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_completion.photo_link
     *
     * @return the value of quest_completion.photo_link
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getPhotoLink() {
        return photoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_completion.photo_link
     *
     * @param photoLink the value for quest_completion.photo_link
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setPhotoLink(String photoLink) {
        this.photoLink = photoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_completion.quest
     *
     * @return the value of quest_completion.quest
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getQuest() {
        return quest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_completion.quest
     *
     * @param quest the value for quest_completion.quest
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setQuest(Long quest) {
        this.quest = quest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_completion.USER
     *
     * @return the value of quest_completion.USER
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_completion.USER
     *
     * @param user the value for quest_completion.USER
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setUser(Long user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", photoLink=").append(photoLink);
        sb.append(", quest=").append(quest);
        sb.append(", user=").append(user);
        sb.append("]");
        return sb.toString();
    }
}