package com.dothings.model;

import java.util.ArrayList;
import java.util.List;

public class QuestCompletionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public QuestCompletionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPhotoLinkIsNull() {
            addCriterion("photo_link is null");
            return (Criteria) this;
        }

        public Criteria andPhotoLinkIsNotNull() {
            addCriterion("photo_link is not null");
            return (Criteria) this;
        }

        public Criteria andPhotoLinkEqualTo(String value) {
            addCriterion("photo_link =", value, "photoLink");
            return (Criteria) this;
        }

        public Criteria andPhotoLinkNotEqualTo(String value) {
            addCriterion("photo_link <>", value, "photoLink");
            return (Criteria) this;
        }

        public Criteria andPhotoLinkGreaterThan(String value) {
            addCriterion("photo_link >", value, "photoLink");
            return (Criteria) this;
        }

        public Criteria andPhotoLinkGreaterThanOrEqualTo(String value) {
            addCriterion("photo_link >=", value, "photoLink");
            return (Criteria) this;
        }

        public Criteria andPhotoLinkLessThan(String value) {
            addCriterion("photo_link <", value, "photoLink");
            return (Criteria) this;
        }

        public Criteria andPhotoLinkLessThanOrEqualTo(String value) {
            addCriterion("photo_link <=", value, "photoLink");
            return (Criteria) this;
        }

        public Criteria andPhotoLinkLike(String value) {
            addCriterion("photo_link like", value, "photoLink");
            return (Criteria) this;
        }

        public Criteria andPhotoLinkNotLike(String value) {
            addCriterion("photo_link not like", value, "photoLink");
            return (Criteria) this;
        }

        public Criteria andPhotoLinkIn(List<String> values) {
            addCriterion("photo_link in", values, "photoLink");
            return (Criteria) this;
        }

        public Criteria andPhotoLinkNotIn(List<String> values) {
            addCriterion("photo_link not in", values, "photoLink");
            return (Criteria) this;
        }

        public Criteria andPhotoLinkBetween(String value1, String value2) {
            addCriterion("photo_link between", value1, value2, "photoLink");
            return (Criteria) this;
        }

        public Criteria andPhotoLinkNotBetween(String value1, String value2) {
            addCriterion("photo_link not between", value1, value2, "photoLink");
            return (Criteria) this;
        }

        public Criteria andQuestIsNull() {
            addCriterion("quest is null");
            return (Criteria) this;
        }

        public Criteria andQuestIsNotNull() {
            addCriterion("quest is not null");
            return (Criteria) this;
        }

        public Criteria andQuestEqualTo(Long value) {
            addCriterion("quest =", value, "quest");
            return (Criteria) this;
        }

        public Criteria andQuestNotEqualTo(Long value) {
            addCriterion("quest <>", value, "quest");
            return (Criteria) this;
        }

        public Criteria andQuestGreaterThan(Long value) {
            addCriterion("quest >", value, "quest");
            return (Criteria) this;
        }

        public Criteria andQuestGreaterThanOrEqualTo(Long value) {
            addCriterion("quest >=", value, "quest");
            return (Criteria) this;
        }

        public Criteria andQuestLessThan(Long value) {
            addCriterion("quest <", value, "quest");
            return (Criteria) this;
        }

        public Criteria andQuestLessThanOrEqualTo(Long value) {
            addCriterion("quest <=", value, "quest");
            return (Criteria) this;
        }

        public Criteria andQuestIn(List<Long> values) {
            addCriterion("quest in", values, "quest");
            return (Criteria) this;
        }

        public Criteria andQuestNotIn(List<Long> values) {
            addCriterion("quest not in", values, "quest");
            return (Criteria) this;
        }

        public Criteria andQuestBetween(Long value1, Long value2) {
            addCriterion("quest between", value1, value2, "quest");
            return (Criteria) this;
        }

        public Criteria andQuestNotBetween(Long value1, Long value2) {
            addCriterion("quest not between", value1, value2, "quest");
            return (Criteria) this;
        }

        public Criteria andUserIsNull() {
            addCriterion("USER is null");
            return (Criteria) this;
        }

        public Criteria andUserIsNotNull() {
            addCriterion("USER is not null");
            return (Criteria) this;
        }

        public Criteria andUserEqualTo(Long value) {
            addCriterion("USER =", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotEqualTo(Long value) {
            addCriterion("USER <>", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserGreaterThan(Long value) {
            addCriterion("USER >", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserGreaterThanOrEqualTo(Long value) {
            addCriterion("USER >=", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserLessThan(Long value) {
            addCriterion("USER <", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserLessThanOrEqualTo(Long value) {
            addCriterion("USER <=", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserIn(List<Long> values) {
            addCriterion("USER in", values, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotIn(List<Long> values) {
            addCriterion("USER not in", values, "user");
            return (Criteria) this;
        }

        public Criteria andUserBetween(Long value1, Long value2) {
            addCriterion("USER between", value1, value2, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotBetween(Long value1, Long value2) {
            addCriterion("USER not between", value1, value2, "user");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table quest_completion
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 06 17:59:21 EET 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table quest_completion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}