package com.dothings.model;

import java.util.Date;

public class Team {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.creation_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.creator_user_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long creatorUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.discontinue_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date discontinueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.is_organizational_team
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Boolean isOrganizationalTeam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.picture
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.teamname
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String teamname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.id
     *
     * @return the value of team.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.id
     *
     * @param id the value for team.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.creation_date
     *
     * @return the value of team.creation_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.creation_date
     *
     * @param creationDate the value for team.creation_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.creator_user_id
     *
     * @return the value of team.creator_user_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getCreatorUserId() {
        return creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.creator_user_id
     *
     * @param creatorUserId the value for team.creator_user_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setCreatorUserId(Long creatorUserId) {
        this.creatorUserId = creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.discontinue_date
     *
     * @return the value of team.discontinue_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getDiscontinueDate() {
        return discontinueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.discontinue_date
     *
     * @param discontinueDate the value for team.discontinue_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setDiscontinueDate(Date discontinueDate) {
        this.discontinueDate = discontinueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.is_organizational_team
     *
     * @return the value of team.is_organizational_team
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Boolean getIsOrganizationalTeam() {
        return isOrganizationalTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.is_organizational_team
     *
     * @param isOrganizationalTeam the value for team.is_organizational_team
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setIsOrganizationalTeam(Boolean isOrganizationalTeam) {
        this.isOrganizationalTeam = isOrganizationalTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.picture
     *
     * @return the value of team.picture
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.picture
     *
     * @param picture the value for team.picture
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.teamname
     *
     * @return the value of team.teamname
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getTeamname() {
        return teamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.teamname
     *
     * @param teamname the value for team.teamname
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setTeamname(String teamname) {
        this.teamname = teamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", creationDate=").append(creationDate);
        sb.append(", creatorUserId=").append(creatorUserId);
        sb.append(", discontinueDate=").append(discontinueDate);
        sb.append(", isOrganizationalTeam=").append(isOrganizationalTeam);
        sb.append(", picture=").append(picture);
        sb.append(", teamname=").append(teamname);
        sb.append("]");
        return sb.toString();
    }
}