package com.dothings.model;

import java.util.Date;

public class TeamMembers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_members.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_members.comment
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_members.date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_members.event_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_members.user_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_members.visible
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Boolean visible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_members.addition_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date additionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_members.discontinue_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date discontinueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_members.is_leader
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Boolean isLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_members.team_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_members.earned_points
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Integer earnedPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_members.event_type
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_members.participant_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long participantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_members.id
     *
     * @return the value of team_members.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_members.id
     *
     * @param id the value for team_members.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_members.comment
     *
     * @return the value of team_members.comment
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_members.comment
     *
     * @param comment the value for team_members.comment
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_members.date
     *
     * @return the value of team_members.date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_members.date
     *
     * @param date the value for team_members.date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_members.event_id
     *
     * @return the value of team_members.event_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_members.event_id
     *
     * @param eventId the value for team_members.event_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_members.user_id
     *
     * @return the value of team_members.user_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_members.user_id
     *
     * @param userId the value for team_members.user_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_members.visible
     *
     * @return the value of team_members.visible
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Boolean getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_members.visible
     *
     * @param visible the value for team_members.visible
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_members.addition_date
     *
     * @return the value of team_members.addition_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getAdditionDate() {
        return additionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_members.addition_date
     *
     * @param additionDate the value for team_members.addition_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setAdditionDate(Date additionDate) {
        this.additionDate = additionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_members.discontinue_date
     *
     * @return the value of team_members.discontinue_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getDiscontinueDate() {
        return discontinueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_members.discontinue_date
     *
     * @param discontinueDate the value for team_members.discontinue_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setDiscontinueDate(Date discontinueDate) {
        this.discontinueDate = discontinueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_members.is_leader
     *
     * @return the value of team_members.is_leader
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Boolean getIsLeader() {
        return isLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_members.is_leader
     *
     * @param isLeader the value for team_members.is_leader
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setIsLeader(Boolean isLeader) {
        this.isLeader = isLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_members.team_id
     *
     * @return the value of team_members.team_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_members.team_id
     *
     * @param teamId the value for team_members.team_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_members.earned_points
     *
     * @return the value of team_members.earned_points
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Integer getEarnedPoints() {
        return earnedPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_members.earned_points
     *
     * @param earnedPoints the value for team_members.earned_points
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setEarnedPoints(Integer earnedPoints) {
        this.earnedPoints = earnedPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_members.event_type
     *
     * @return the value of team_members.event_type
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_members.event_type
     *
     * @param eventType the value for team_members.event_type
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_members.participant_id
     *
     * @return the value of team_members.participant_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getParticipantId() {
        return participantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_members.participant_id
     *
     * @param participantId the value for team_members.participant_id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setParticipantId(Long participantId) {
        this.participantId = participantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_members
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", comment=").append(comment);
        sb.append(", date=").append(date);
        sb.append(", eventId=").append(eventId);
        sb.append(", userId=").append(userId);
        sb.append(", visible=").append(visible);
        sb.append(", additionDate=").append(additionDate);
        sb.append(", discontinueDate=").append(discontinueDate);
        sb.append(", isLeader=").append(isLeader);
        sb.append(", teamId=").append(teamId);
        sb.append(", earnedPoints=").append(earnedPoints);
        sb.append(", eventType=").append(eventType);
        sb.append(", participantId=").append(participantId);
        sb.append("]");
        return sb.toString();
    }
}