package com.dothings.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.date_created
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.department
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.display_name
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.experience
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Integer experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_login_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Date lastLoginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.profile_picture
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String profilePicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.rank
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sleep
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Double sleep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.title
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.walk
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Double walk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.water
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    private Double water;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.date_created
     *
     * @return the value of user.date_created
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.date_created
     *
     * @param dateCreated the value for user.date_created
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.department
     *
     * @return the value of user.department
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.department
     *
     * @param department the value for user.department
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.display_name
     *
     * @return the value of user.display_name
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.display_name
     *
     * @param displayName the value for user.display_name
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.experience
     *
     * @return the value of user.experience
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Integer getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.experience
     *
     * @param experience the value for user.experience
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_login_date
     *
     * @return the value of user.last_login_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_login_date
     *
     * @param lastLoginDate the value for user.last_login_date
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.profile_picture
     *
     * @return the value of user.profile_picture
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getProfilePicture() {
        return profilePicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.profile_picture
     *
     * @param profilePicture the value for user.profile_picture
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.rank
     *
     * @return the value of user.rank
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.rank
     *
     * @param rank the value for user.rank
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sleep
     *
     * @return the value of user.sleep
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Double getSleep() {
        return sleep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sleep
     *
     * @param sleep the value for user.sleep
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setSleep(Double sleep) {
        this.sleep = sleep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.title
     *
     * @return the value of user.title
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.title
     *
     * @param title the value for user.title
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.walk
     *
     * @return the value of user.walk
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Double getWalk() {
        return walk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.walk
     *
     * @param walk the value for user.walk
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setWalk(Double walk) {
        this.walk = walk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.water
     *
     * @return the value of user.water
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public Double getWater() {
        return water;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.water
     *
     * @param water the value for user.water
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    public void setWater(Double water) {
        this.water = water;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dateCreated=").append(dateCreated);
        sb.append(", department=").append(department);
        sb.append(", displayName=").append(displayName);
        sb.append(", email=").append(email);
        sb.append(", experience=").append(experience);
        sb.append(", lastLoginDate=").append(lastLoginDate);
        sb.append(", password=").append(password);
        sb.append(", profilePicture=").append(profilePicture);
        sb.append(", rank=").append(rank);
        sb.append(", sleep=").append(sleep);
        sb.append(", title=").append(title);
        sb.append(", walk=").append(walk);
        sb.append(", water=").append(water);
        sb.append("]");
        return sb.toString();
    }
}