package com.dothings.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.dothings.model.EventCompletion;
import com.dothings.model.EventCompletionExample;

public interface EventCompletionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventcompletion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int countByExample(EventCompletionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventcompletion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int deleteByExample(EventCompletionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventcompletion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventcompletion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int insert(EventCompletion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventcompletion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int insertSelective(EventCompletion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventcompletion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    List<EventCompletion> selectByExample(EventCompletionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventcompletion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    EventCompletion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventcompletion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int updateByExampleSelective(@Param("record") EventCompletion record, @Param("example") EventCompletionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventcompletion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int updateByExample(@Param("record") EventCompletion record, @Param("example") EventCompletionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventcompletion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int updateByPrimaryKeySelective(EventCompletion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventcompletion
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int updateByPrimaryKey(EventCompletion record);
}