package com.dothings.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.dothings.model.HealthDetail;
import com.dothings.model.HealthDetailExample;

public interface HealthDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_detail
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    int countByExample(HealthDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_detail
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    int deleteByExample(HealthDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_detail
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_detail
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    int insert(HealthDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_detail
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    int insertSelective(HealthDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_detail
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    List<HealthDetail> selectByExample(HealthDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_detail
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    HealthDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_detail
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    int updateByExampleSelective(@Param("record") HealthDetail record, @Param("example") HealthDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_detail
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    int updateByExample(@Param("record") HealthDetail record, @Param("example") HealthDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_detail
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    int updateByPrimaryKeySelective(HealthDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_detail
     *
     * @mbggenerated Sun Dec 06 17:59:53 EET 2015
     */
    int updateByPrimaryKey(HealthDetail record);
}