package com.dothings.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.dothings.model.Poll;
import com.dothings.model.PollExample;

public interface PollMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int countByExample(PollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int deleteByExample(PollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int insert(Poll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int insertSelective(Poll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    List<Poll> selectByExample(PollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    Poll selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int updateByExampleSelective(@Param("record") Poll record, @Param("example") PollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int updateByExample(@Param("record") Poll record, @Param("example") PollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int updateByPrimaryKeySelective(Poll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int updateByPrimaryKey(Poll record);
}