package com.dothings.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.dothings.model.PollAnswer;
import com.dothings.model.PollAnswerExample;

public interface PollAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int countByExample(PollAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int deleteByExample(PollAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int insert(PollAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int insertSelective(PollAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    List<PollAnswer> selectByExample(PollAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    PollAnswer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int updateByExampleSelective(@Param("record") PollAnswer record, @Param("example") PollAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int updateByExample(@Param("record") PollAnswer record, @Param("example") PollAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int updateByPrimaryKeySelective(PollAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answer
     *
     * @mbggenerated Sun Dec 06 17:59:21 EET 2015
     */
    int updateByPrimaryKey(PollAnswer record);
}